export const generateNdf4wLowRiskPayload = (params = {}) => ({
  "$.asset.asset_code": "DAIHATSU.ROCKY.M12AT",
  "$.asset.bpkb_ownership": "1",
  "$.asset.bpkb_status": "on_hand",
  "$.asset.license_plate": params.licensePlate,
  "$.asset.manufacturing_year": "2024",
  "$.asset.stnk_status": "ACTIVE",
  "$.asset.tax_status": "tax_paid_off",
  "$.channel.activity_id": "DPBR",
  "$.channel.ekyc_authority": "partner",
  "$.channel.ktp_forgery_authority": "partner",
  "$.channel.ktp_ocr_required": false,
  "$.channel.marketing_id": "2311NC0006",
  "$.channel.partner_id": "15871124-0258-4e3f-9f31-bc995e348a8d",
  "$.channel.partner_internal_name": "partner-goto",
  "$.channel.signing_processor": "manual",
  "$.channel.soa_id": "28",
  "$.customer.bank_information.account_name": "MULTIFINANCE ANAK BANGSA GOTO",
  "$.customer.bank_information.account_number": "0010988888",
  "$.customer.bank_information.bank_id": 47,
  "$.customer.contact.email": "LULLABYANGEL22@GMAIL.COM",
  "$.customer.contact.mobile_number": "+6281234567890",
  "$.customer.domicile.address.street_address": "JL KEBAGUSAN AJA",
  "$.customer.domicile.address.sub_district_code": "36.74.01.1005",
  "$.customer.domicile.ownership_code": "SD",
  "$.customer.ktp.birth_date": "1990-10-31",
  "$.customer.ktp.birth_place": "MANOKWARI",
  "$.customer.ktp.city": "Tangerang Selatan",
  "$.customer.ktp.district": "Serpong",
  "$.customer.ktp.gender": "M",
  "$.customer.ktp.name": params.customerName,
  "$.customer.ktp.nik": "3154497112754229",
  "$.customer.ktp.province": "Banten",
  "$.customer.ktp.street_address": "JALAN JALAN",
  "$.customer.ktp.sub_district": "Lengkong Wetan",
  "$.customer.ktp.sub_district_code": "36.74.01.1005",
  "$.customer.ktp.zip_code": "15322",
  "$.customer.personal.marital_status_code": "S",
  "$.customer.personal.number_dependents": "1",
  "$.customer.professional.education_code": "S1",
  "$.customer.professional.length_current_job": "LESS_THAN_15",
  "$.customer.professional.monthly_income": "200000000",
  "$.customer.professional.npwp": "640207610689009",
  "$.customer.professional.npwp_matches_nik": false,
  "$.customer.professional.occupation_type_code": "M",
  "$.documents.ktp.document_id": "cc834b4b-270a-447c-8590-5ce2467fd136",
  "$.documents.selfie.document_id": "e583bb72-2941-4ff3-8469-37adfea07768",
  "$.loan_structure.original_amount": 13500000,
  "$.loan_structure.product_id": 1,
  "$.loan_structure.product_offering": 32,
  "$.loan_structure.tenure": 12,
  "$.process.user_consent_timestamp": "2025-11-10T03:47:38.475379835Z"
})
